version: '3.7'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  mongo-seed:
    image: mongo:latest
    links:
      - mongodb
    volumes:
      - ./db/data:/usr/src/data
    command:
      /usr/src/data/import.sh

  graphql:
    build:
      context: ./server 
    links:
      - mongodb
    ports:
      - "49160:4000"
